steps:
  # Build + publish image with buildpacks
  - name: "gcr.io/k8s-skaffold/pack"
    args:
      [
        "build",
        "asia-south2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/voice-agent-api:$COMMIT_SHA",
        "--builder",
        "gcr.io/buildpacks/builder",
        "--publish"
      ]

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "voice-agent-api",
        "--image", "asia-south2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/voice-agent-api:$COMMIT_SHA",
        "--region", "asia-south2",
        "--platform", "managed",
        "--quiet"
      ]

images:
  - "asia-south2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/voice-agent-api:$COMMIT_SHA"

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
